{
 "title": "Flow Monitoring",
 "time": { "from": "2020-01-20T09:22:40.000Z", "to": "2020-01-20T09:28:48.000Z" },
 "templating": {
  "list": [
   {
    "name": "srcip",
    "query": "SHOW TAG VALUES ON \"int_telemetry\" WITH KEY = \"srcip\""
   },
   {
    "name": "dstip",
    "query": "SHOW TAG VALUES ON \"int_telemetry\" WITH KEY = \"dstip\" WHERE \"srcip\"='${srcip:query}'"
   }
  ]
 },
 "panels": [
  {
   "title": "Delay Average",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "format": "ns",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"dstts\" - \"origts\" FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jiter Average",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "format": "ns",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT DIFFERENCE(\"dstts\") FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}' ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reordering Average",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT DIFFERENCE(\"seq\") FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}' ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}' ORDER BY asc\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Delay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"dstts\" - \"origts\" FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Seq",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"seq\" FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT DIFFERENCE(\"dstts\") FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}' ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reordering",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT DIFFERENCE(\"seq\") FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}' ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of incoming packets",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT COUNT(\"dstts\") FROM int_telemetry.flow_monitoring_policy.int_telemetry WHERE \"srcip\" = '${srcip:query}' AND \"dstip\" = '${dstip:query}' group by time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}