{
 "title": "INT Monitoring of FBK flow (continuous influx query)",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "INT-source and INT-sink timestamp difference (\"delay\")",
   "type": "graph",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "timestamps diff",
     "measurement": "int_telemetry",
     "query": "select mean_delay from int_averaged_100ms where $timeFilter  ",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Pkt/s" }
   ],
   "targets": [
    {
     "alias": "pkt rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "int_telemetry",
     "query": "select pps from int_averaged_100ms where $timeFilter  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Inter-Arrival Time (IAT)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "IAT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "int_telemetry",
     "query": "select mean_jitter from int_averaged_100ms where $timeFilter  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reordering",
   "type": "graph",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "reordering",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "int_telemetry",
     "query": "select mean_reordering from int_averaged_100ms where $timeFilter  ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}