{
 "title": "INT Monitoring compact (time-averaging)",
 "time": { "from": "now-2m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "srcip",
    "query": "SHOW TAG VALUES ON \"int_telemetry_db\" WITH KEY = \"srcip\""
   },
   {
    "name": "dstip",
    "query": "SHOW TAG VALUES ON \"int_telemetry_db\" WITH KEY = \"dstip\" WHERE \"srcip\" =~ /^$srcip$/"
   }
  ]
 },
 "panels": [
  {
   "title": "INT-source and INT-sink timestamp difference (\"delay\")",
   "type": "graph",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "timestamp diff",
     "measurement": "int_telemetry",
     "query": "SELECT mean(delay) FROM int_telemetry  WHERE (\"srcip\" =~ /^$srcip$/ AND \"dstip\" =~ /^$dstip$/) AND $timeFilter  GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet rate",
   "type": "graph",
   "gridPos": { "h": 13, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Pkt/s" }
   ],
   "targets": [
    {
     "alias": "pkt rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "int_telemetry",
     "query": "SELECT count(\"dstts\") FROM int_telemetry WHERE (\"srcip\" =~ /^$srcip$/ AND \"dstip\" =~ /^$dstip$/) AND $timeFilter GROUP BY time(1s) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet Inter-Arrival Time (IAT)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "IAT",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "int_telemetry",
     "query": "SELECT mean(\"sink_jitter\") FROM int_telemetry WHERE (\"srcip\" =~ /^$srcip$/ AND \"dstip\" =~ /^$dstip$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Reordering",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "none", "label": "reordering factor" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "int_telemetry",
     "query": "SELECT mean(\"reordering\") FROM int_telemetry WHERE (\"srcip\" =~ /^$srcip$/ AND \"dstip\" =~ /^$dstip$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data table",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT * FROM int_telemetry WHERE (\"srcip\" =~ /^$srcip$/ AND \"dstip\" =~ /^$dstip$/) ORDER BY time DESC LIMIT 10\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}